# render.yaml (Final Refactored Version)

services:
  # Public-facing gateway service
  - type: web
    name: gateway
    runtime: docker
    dockerContext: ./gateway
    healthCheckPath: /health
    envVars:
      - key: SERVICE_A_URL
        value: http://service-a:10000
      - key: SERVICE_B_URL
        value: http://service-b:10000
      - key: SERVICE_C_URL
        value: http://service-c:10000
      - key: FALLBACK_URL
        value: http://fallback:10000

  # Private microservices
  - type: pserv
    name: service-a
    runtime: docker
    dockerContext: ./service_a
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  - type: pserv
    name: service-b
    runtime: docker
    dockerContext: ./service_b
    healthCheckPath: /health
    envVars:
      - key: FAIL_RATE
        value: "0.2"

  - type: pserv
    name: service-c
    runtime: docker
    dockerContext: ./service_c
    healthCheckPath: /health

  - type: pserv
    name: fallback
    runtime: docker
    dockerContext: ./fallback
    healthCheckPath: /health

# Managed Redis instance
databases:
  - name: redis
    plan: free
